//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.MVC.DataServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataServiceClient.IEWEDataService")]
    public interface IEWEDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetSurveyInfo", ReplyAction="http://tempuri.org/IEWEDataService/GetSurveyInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetSurveyInfoCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.SurveyInfoResponse GetSurveyInfo(Epi.Web.Enter.Common.Message.SurveyInfoRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetSurveyAnswer", ReplyAction="http://tempuri.org/IEWEDataService/GetSurveyAnswerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetSurveyAnswerCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.SurveyAnswerResponse GetSurveyAnswer(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/SetSurveyAnswer", ReplyAction="http://tempuri.org/IEWEDataService/SetSurveyAnswerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/SetSurveyAnswerCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.SurveyAnswerResponse SetSurveyAnswer(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/PassCodeLogin", ReplyAction="http://tempuri.org/IEWEDataService/PassCodeLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/PassCodeLoginCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.UserAuthenticationResponse PassCodeLogin(Epi.Web.Enter.Common.Message.UserAuthenticationRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/SetPassCode", ReplyAction="http://tempuri.org/IEWEDataService/SetPassCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/SetPassCodeCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.UserAuthenticationResponse SetPassCode(Epi.Web.Enter.Common.Message.UserAuthenticationRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetAuthenticationResponse", ReplyAction="http://tempuri.org/IEWEDataService/GetAuthenticationResponseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetAuthenticationResponseCustomFaultExceptionF" +
            "ault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.UserAuthenticationResponse GetAuthenticationResponse(Epi.Web.Enter.Common.Message.UserAuthenticationRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetFormsInfo", ReplyAction="http://tempuri.org/IEWEDataService/GetFormsInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetFormsInfoCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.FormsInfoResponse GetFormsInfo(Epi.Web.Enter.Common.Message.FormsInfoRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetFormResponseInfo", ReplyAction="http://tempuri.org/IEWEDataService/GetFormResponseInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetFormResponseInfoCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.FormResponseInfoResponse GetFormResponseInfo(Epi.Web.Enter.Common.Message.FormResponseInfoRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetFormResponseList", ReplyAction="http://tempuri.org/IEWEDataService/GetFormResponseListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetFormResponseListCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.SurveyAnswerResponse GetFormResponseList(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetFormSettings", ReplyAction="http://tempuri.org/IEWEDataService/GetFormSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetFormSettingsCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.FormSettingResponse GetFormSettings(Epi.Web.Enter.Common.Message.FormSettingRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/DeleteResponse", ReplyAction="http://tempuri.org/IEWEDataService/DeleteResponseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/DeleteResponseCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.SurveyAnswerResponse DeleteResponse(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/UserLogin", ReplyAction="http://tempuri.org/IEWEDataService/UserLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/UserLoginCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.UserAuthenticationResponse UserLogin(Epi.Web.Enter.Common.Message.UserAuthenticationRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetUser", ReplyAction="http://tempuri.org/IEWEDataService/GetUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetUserCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.UserAuthenticationResponse GetUser(Epi.Web.Enter.Common.Message.UserAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/UpdateUser", ReplyAction="http://tempuri.org/IEWEDataService/UpdateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/UpdateUserCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        bool UpdateUser(Epi.Web.Enter.Common.Message.UserAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/SaveSettings", ReplyAction="http://tempuri.org/IEWEDataService/SaveSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/SaveSettingsCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.FormSettingResponse SaveSettings(Epi.Web.Enter.Common.Message.FormSettingRequest FormSettingReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetFormChildInfo", ReplyAction="http://tempuri.org/IEWEDataService/GetFormChildInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetFormChildInfoCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.SurveyInfoResponse GetFormChildInfo(Epi.Web.Enter.Common.Message.SurveyInfoRequest SurveyInfoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetFormsHierarchy", ReplyAction="http://tempuri.org/IEWEDataService/GetFormsHierarchyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetFormsHierarchyCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.FormsHierarchyResponse GetFormsHierarchy(Epi.Web.Enter.Common.Message.FormsHierarchyRequest FormsHierarchyRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetSurveyAnswerHierarchy", ReplyAction="http://tempuri.org/IEWEDataService/GetSurveyAnswerHierarchyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetSurveyAnswerHierarchyCustomFaultExceptionFa" +
            "ult", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.SurveyAnswerResponse GetSurveyAnswerHierarchy(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetAncestorResponseIdsByChildId", ReplyAction="http://tempuri.org/IEWEDataService/GetAncestorResponseIdsByChildIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetAncestorResponseIdsByChildIdCustomFaultExce" +
            "ptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.SurveyAnswerResponse GetAncestorResponseIdsByChildId(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetResponsesByRelatedFormId", ReplyAction="http://tempuri.org/IEWEDataService/GetResponsesByRelatedFormIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetResponsesByRelatedFormIdCustomFaultExceptio" +
            "nFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.SurveyAnswerResponse GetResponsesByRelatedFormId(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetOrganizationsByUserId", ReplyAction="http://tempuri.org/IEWEDataService/GetOrganizationsByUserIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetOrganizationsByUserIdCustomFaultExceptionFa" +
            "ult", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.OrganizationResponse GetOrganizationsByUserId(Epi.Web.Enter.Common.Message.OrganizationRequest OrgRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetUserOrganizations", ReplyAction="http://tempuri.org/IEWEDataService/GetUserOrganizationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetUserOrganizationsCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.OrganizationResponse GetUserOrganizations(Epi.Web.Enter.Common.Message.OrganizationRequest OrgRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetAdminOrganizations", ReplyAction="http://tempuri.org/IEWEDataService/GetAdminOrganizationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetAdminOrganizationsCustomFaultExceptionFault" +
            "", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.OrganizationResponse GetAdminOrganizations(Epi.Web.Enter.Common.Message.OrganizationRequest OrgRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetOrganizationInfo", ReplyAction="http://tempuri.org/IEWEDataService/GetOrganizationInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetOrganizationInfoCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.OrganizationResponse GetOrganizationInfo(Epi.Web.Enter.Common.Message.OrganizationRequest OrgRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/SetOrganization", ReplyAction="http://tempuri.org/IEWEDataService/SetOrganizationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/SetOrganizationCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.OrganizationResponse SetOrganization(Epi.Web.Enter.Common.Message.OrganizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetOrganizationUsers", ReplyAction="http://tempuri.org/IEWEDataService/GetOrganizationUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetOrganizationUsersCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.OrganizationResponse GetOrganizationUsers(Epi.Web.Enter.Common.Message.OrganizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/GetUserInfo", ReplyAction="http://tempuri.org/IEWEDataService/GetUserInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/GetUserInfoCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.UserResponse GetUserInfo(Epi.Web.Enter.Common.Message.UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/SetUserInfo", ReplyAction="http://tempuri.org/IEWEDataService/SetUserInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/SetUserInfoCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.Web.Enter.Common.Message.UserResponse SetUserInfo(Epi.Web.Enter.Common.Message.UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/UpdateResponseStatus", ReplyAction="http://tempuri.org/IEWEDataService/UpdateResponseStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/UpdateResponseStatusCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        void UpdateResponseStatus(Epi.Web.Enter.Common.Message.SurveyAnswerRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWEDataService/HasResponse", ReplyAction="http://tempuri.org/IEWEDataService/HasResponseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.Web.Enter.Common.Exception.CustomFaultException), Action="http://tempuri.org/IEWEDataService/HasResponseCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        bool HasResponse(string SurveyId, string ResponseId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEWEDataServiceChannel : Epi.Web.MVC.DataServiceClient.IEWEDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EWEDataServiceClient : System.ServiceModel.ClientBase<Epi.Web.MVC.DataServiceClient.IEWEDataService>, Epi.Web.MVC.DataServiceClient.IEWEDataService {
        
        public EWEDataServiceClient() {
        }
        
        public EWEDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EWEDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EWEDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EWEDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Epi.Web.Enter.Common.Message.SurveyInfoResponse GetSurveyInfo(Epi.Web.Enter.Common.Message.SurveyInfoRequest pRequest) {
            return base.Channel.GetSurveyInfo(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.SurveyAnswerResponse GetSurveyAnswer(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest) {
            return base.Channel.GetSurveyAnswer(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.SurveyAnswerResponse SetSurveyAnswer(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest) {
            return base.Channel.SetSurveyAnswer(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.UserAuthenticationResponse PassCodeLogin(Epi.Web.Enter.Common.Message.UserAuthenticationRequest pRequest) {
            return base.Channel.PassCodeLogin(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.UserAuthenticationResponse SetPassCode(Epi.Web.Enter.Common.Message.UserAuthenticationRequest pRequest) {
            return base.Channel.SetPassCode(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.UserAuthenticationResponse GetAuthenticationResponse(Epi.Web.Enter.Common.Message.UserAuthenticationRequest pRequest) {
            return base.Channel.GetAuthenticationResponse(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.FormsInfoResponse GetFormsInfo(Epi.Web.Enter.Common.Message.FormsInfoRequest pRequest) {
            return base.Channel.GetFormsInfo(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.FormResponseInfoResponse GetFormResponseInfo(Epi.Web.Enter.Common.Message.FormResponseInfoRequest pRequest) {
            return base.Channel.GetFormResponseInfo(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.SurveyAnswerResponse GetFormResponseList(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest) {
            return base.Channel.GetFormResponseList(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.FormSettingResponse GetFormSettings(Epi.Web.Enter.Common.Message.FormSettingRequest pRequest) {
            return base.Channel.GetFormSettings(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.SurveyAnswerResponse DeleteResponse(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest) {
            return base.Channel.DeleteResponse(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.UserAuthenticationResponse UserLogin(Epi.Web.Enter.Common.Message.UserAuthenticationRequest pRequest) {
            return base.Channel.UserLogin(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.UserAuthenticationResponse GetUser(Epi.Web.Enter.Common.Message.UserAuthenticationRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public bool UpdateUser(Epi.Web.Enter.Common.Message.UserAuthenticationRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public Epi.Web.Enter.Common.Message.FormSettingResponse SaveSettings(Epi.Web.Enter.Common.Message.FormSettingRequest FormSettingReq) {
            return base.Channel.SaveSettings(FormSettingReq);
        }
        
        public Epi.Web.Enter.Common.Message.SurveyInfoResponse GetFormChildInfo(Epi.Web.Enter.Common.Message.SurveyInfoRequest SurveyInfoRequest) {
            return base.Channel.GetFormChildInfo(SurveyInfoRequest);
        }
        
        public Epi.Web.Enter.Common.Message.FormsHierarchyResponse GetFormsHierarchy(Epi.Web.Enter.Common.Message.FormsHierarchyRequest FormsHierarchyRequest) {
            return base.Channel.GetFormsHierarchy(FormsHierarchyRequest);
        }
        
        public Epi.Web.Enter.Common.Message.SurveyAnswerResponse GetSurveyAnswerHierarchy(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest) {
            return base.Channel.GetSurveyAnswerHierarchy(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.SurveyAnswerResponse GetAncestorResponseIdsByChildId(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest) {
            return base.Channel.GetAncestorResponseIdsByChildId(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.SurveyAnswerResponse GetResponsesByRelatedFormId(Epi.Web.Enter.Common.Message.SurveyAnswerRequest pRequest) {
            return base.Channel.GetResponsesByRelatedFormId(pRequest);
        }
        
        public Epi.Web.Enter.Common.Message.OrganizationResponse GetOrganizationsByUserId(Epi.Web.Enter.Common.Message.OrganizationRequest OrgRequest) {
            return base.Channel.GetOrganizationsByUserId(OrgRequest);
        }
        
        public Epi.Web.Enter.Common.Message.OrganizationResponse GetUserOrganizations(Epi.Web.Enter.Common.Message.OrganizationRequest OrgRequest) {
            return base.Channel.GetUserOrganizations(OrgRequest);
        }
        
        public Epi.Web.Enter.Common.Message.OrganizationResponse GetAdminOrganizations(Epi.Web.Enter.Common.Message.OrganizationRequest OrgRequest) {
            return base.Channel.GetAdminOrganizations(OrgRequest);
        }
        
        public Epi.Web.Enter.Common.Message.OrganizationResponse GetOrganizationInfo(Epi.Web.Enter.Common.Message.OrganizationRequest OrgRequest) {
            return base.Channel.GetOrganizationInfo(OrgRequest);
        }
        
        public Epi.Web.Enter.Common.Message.OrganizationResponse SetOrganization(Epi.Web.Enter.Common.Message.OrganizationRequest request) {
            return base.Channel.SetOrganization(request);
        }
        
        public Epi.Web.Enter.Common.Message.OrganizationResponse GetOrganizationUsers(Epi.Web.Enter.Common.Message.OrganizationRequest request) {
            return base.Channel.GetOrganizationUsers(request);
        }
        
        public Epi.Web.Enter.Common.Message.UserResponse GetUserInfo(Epi.Web.Enter.Common.Message.UserRequest request) {
            return base.Channel.GetUserInfo(request);
        }
        
        public Epi.Web.Enter.Common.Message.UserResponse SetUserInfo(Epi.Web.Enter.Common.Message.UserRequest request) {
            return base.Channel.SetUserInfo(request);
        }
        
        public void UpdateResponseStatus(Epi.Web.Enter.Common.Message.SurveyAnswerRequest Request) {
            base.Channel.UpdateResponseStatus(Request);
        }
        
        public bool HasResponse(string SurveyId, string ResponseId) {
            return base.Channel.HasResponse(SurveyId, ResponseId);
        }
    }
}
