//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public System.Guid AdminId { get; set; }
        public string AdminEmail { get; set; }
        public int OrganizationId { get; set; }
        public bool IsActive { get; set; }
        public bool Notify { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
