//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canva
    {
        public int CanvasID { get; set; }
        public System.Guid CanvasGUID { get; set; }
        public string CanvasName { get; set; }
        public int UserID { get; set; }
        public string CanvasDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DatasourceID { get; set; }
        public string CanvasContent { get; set; }
    
        public virtual User User { get; set; }
    }
}
