//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("OSELS_EWEModel", "FK_Admin_Organization", "Organization", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Epi.Web.EF.Organization), "Admin", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Epi.Web.EF.Admin), true)]
[assembly: EdmRelationshipAttribute("OSELS_EWEModel", "FK_SurveyResponse_lk_Status", "lk_Status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Epi.Web.EF.lk_Status), "SurveyResponse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Epi.Web.EF.SurveyResponse), true)]
[assembly: EdmRelationshipAttribute("OSELS_EWEModel", "FK_SurveyMetaData_lk_SurveyType", "lk_SurveyType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Epi.Web.EF.lk_SurveyType), "SurveyMetaData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Epi.Web.EF.SurveyMetaData), true)]
[assembly: EdmRelationshipAttribute("OSELS_EWEModel", "FK_SurveyMetaData_Organization", "Organization", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Epi.Web.EF.Organization), "SurveyMetaData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Epi.Web.EF.SurveyMetaData), true)]
[assembly: EdmRelationshipAttribute("OSELS_EWEModel", "FK_SurveyResponse_SurveyMetaData", "SurveyMetaData", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Epi.Web.EF.SurveyMetaData), "SurveyResponse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Epi.Web.EF.SurveyResponse), true)]

#endregion

namespace Epi.Web.EF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OSELS_EWEEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OSELS_EWEEntities object using the connection string found in the 'OSELS_EWEEntities' section of the application configuration file.
        /// </summary>
        public OSELS_EWEEntities() : base("name=OSELS_EWEEntities", "OSELS_EWEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OSELS_EWEEntities object.
        /// </summary>
        public OSELS_EWEEntities(string connectionString) : base(connectionString, "OSELS_EWEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OSELS_EWEEntities object.
        /// </summary>
        public OSELS_EWEEntities(EntityConnection connection) : base(connection, "OSELS_EWEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Admin> Admins
        {
            get
            {
                if ((_Admins == null))
                {
                    _Admins = base.CreateObjectSet<Admin>("Admins");
                }
                return _Admins;
            }
        }
        private ObjectSet<Admin> _Admins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lk_Status> lk_Status
        {
            get
            {
                if ((_lk_Status == null))
                {
                    _lk_Status = base.CreateObjectSet<lk_Status>("lk_Status");
                }
                return _lk_Status;
            }
        }
        private ObjectSet<lk_Status> _lk_Status;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lk_SurveyType> lk_SurveyType
        {
            get
            {
                if ((_lk_SurveyType == null))
                {
                    _lk_SurveyType = base.CreateObjectSet<lk_SurveyType>("lk_SurveyType");
                }
                return _lk_SurveyType;
            }
        }
        private ObjectSet<lk_SurveyType> _lk_SurveyType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Organization> Organizations
        {
            get
            {
                if ((_Organizations == null))
                {
                    _Organizations = base.CreateObjectSet<Organization>("Organizations");
                }
                return _Organizations;
            }
        }
        private ObjectSet<Organization> _Organizations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SurveyMetaData> SurveyMetaDatas
        {
            get
            {
                if ((_SurveyMetaDatas == null))
                {
                    _SurveyMetaDatas = base.CreateObjectSet<SurveyMetaData>("SurveyMetaDatas");
                }
                return _SurveyMetaDatas;
            }
        }
        private ObjectSet<SurveyMetaData> _SurveyMetaDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SurveyResponse> SurveyResponses
        {
            get
            {
                if ((_SurveyResponses == null))
                {
                    _SurveyResponses = base.CreateObjectSet<SurveyResponse>("SurveyResponses");
                }
                return _SurveyResponses;
            }
        }
        private ObjectSet<SurveyResponse> _SurveyResponses;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Admins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdmins(Admin admin)
        {
            base.AddObject("Admins", admin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lk_Status EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolk_Status(lk_Status lk_Status)
        {
            base.AddObject("lk_Status", lk_Status);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lk_SurveyType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolk_SurveyType(lk_SurveyType lk_SurveyType)
        {
            base.AddObject("lk_SurveyType", lk_SurveyType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Organizations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrganizations(Organization organization)
        {
            base.AddObject("Organizations", organization);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SurveyMetaDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurveyMetaDatas(SurveyMetaData surveyMetaData)
        {
            base.AddObject("SurveyMetaDatas", surveyMetaData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SurveyResponses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurveyResponses(SurveyResponse surveyResponse)
        {
            base.AddObject("SurveyResponses", surveyResponse);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OSELS_EWEModel", Name="Admin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Admin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Admin object.
        /// </summary>
        /// <param name="adminId">Initial value of the AdminId property.</param>
        /// <param name="adminEmail">Initial value of the AdminEmail property.</param>
        /// <param name="organizationId">Initial value of the OrganizationId property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        /// <param name="notify">Initial value of the Notify property.</param>
        public static Admin CreateAdmin(global::System.Guid adminId, global::System.String adminEmail, global::System.Int32 organizationId, global::System.Boolean isActive, global::System.Boolean notify)
        {
            Admin admin = new Admin();
            admin.AdminId = adminId;
            admin.AdminEmail = adminEmail;
            admin.OrganizationId = organizationId;
            admin.IsActive = isActive;
            admin.Notify = notify;
            return admin;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid AdminId
        {
            get
            {
                return _AdminId;
            }
            set
            {
                if (_AdminId != value)
                {
                    OnAdminIdChanging(value);
                    ReportPropertyChanging("AdminId");
                    _AdminId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AdminId");
                    OnAdminIdChanged();
                }
            }
        }
        private global::System.Guid _AdminId;
        partial void OnAdminIdChanging(global::System.Guid value);
        partial void OnAdminIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AdminEmail
        {
            get
            {
                return _AdminEmail;
            }
            set
            {
                OnAdminEmailChanging(value);
                ReportPropertyChanging("AdminEmail");
                _AdminEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AdminEmail");
                OnAdminEmailChanged();
            }
        }
        private global::System.String _AdminEmail;
        partial void OnAdminEmailChanging(global::System.String value);
        partial void OnAdminEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                OnOrganizationIdChanging(value);
                ReportPropertyChanging("OrganizationId");
                _OrganizationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrganizationId");
                OnOrganizationIdChanged();
            }
        }
        private global::System.Int32 _OrganizationId;
        partial void OnOrganizationIdChanging(global::System.Int32 value);
        partial void OnOrganizationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Notify
        {
            get
            {
                return _Notify;
            }
            set
            {
                OnNotifyChanging(value);
                ReportPropertyChanging("Notify");
                _Notify = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Notify");
                OnNotifyChanged();
            }
        }
        private global::System.Boolean _Notify;
        partial void OnNotifyChanging(global::System.Boolean value);
        partial void OnNotifyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OSELS_EWEModel", "FK_Admin_Organization", "Organization")]
        public Organization Organization
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("OSELS_EWEModel.FK_Admin_Organization", "Organization").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("OSELS_EWEModel.FK_Admin_Organization", "Organization").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Organization> OrganizationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("OSELS_EWEModel.FK_Admin_Organization", "Organization");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Organization>("OSELS_EWEModel.FK_Admin_Organization", "Organization", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OSELS_EWEModel", Name="lk_Status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lk_Status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lk_Status object.
        /// </summary>
        /// <param name="statusId">Initial value of the StatusId property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static lk_Status Createlk_Status(global::System.Int32 statusId, global::System.String status)
        {
            lk_Status lk_Status = new lk_Status();
            lk_Status.StatusId = statusId;
            lk_Status.Status = status;
            return lk_Status;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                if (_StatusId != value)
                {
                    OnStatusIdChanging(value);
                    ReportPropertyChanging("StatusId");
                    _StatusId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StatusId");
                    OnStatusIdChanged();
                }
            }
        }
        private global::System.Int32 _StatusId;
        partial void OnStatusIdChanging(global::System.Int32 value);
        partial void OnStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OSELS_EWEModel", "FK_SurveyResponse_lk_Status", "SurveyResponse")]
        public EntityCollection<SurveyResponse> SurveyResponses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SurveyResponse>("OSELS_EWEModel.FK_SurveyResponse_lk_Status", "SurveyResponse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SurveyResponse>("OSELS_EWEModel.FK_SurveyResponse_lk_Status", "SurveyResponse", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OSELS_EWEModel", Name="lk_SurveyType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lk_SurveyType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lk_SurveyType object.
        /// </summary>
        /// <param name="surveyTypeId">Initial value of the SurveyTypeId property.</param>
        public static lk_SurveyType Createlk_SurveyType(global::System.Int32 surveyTypeId)
        {
            lk_SurveyType lk_SurveyType = new lk_SurveyType();
            lk_SurveyType.SurveyTypeId = surveyTypeId;
            return lk_SurveyType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SurveyTypeId
        {
            get
            {
                return _SurveyTypeId;
            }
            set
            {
                if (_SurveyTypeId != value)
                {
                    OnSurveyTypeIdChanging(value);
                    ReportPropertyChanging("SurveyTypeId");
                    _SurveyTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SurveyTypeId");
                    OnSurveyTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _SurveyTypeId;
        partial void OnSurveyTypeIdChanging(global::System.Int32 value);
        partial void OnSurveyTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SurveyType
        {
            get
            {
                return _SurveyType;
            }
            set
            {
                OnSurveyTypeChanging(value);
                ReportPropertyChanging("SurveyType");
                _SurveyType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SurveyType");
                OnSurveyTypeChanged();
            }
        }
        private global::System.String _SurveyType;
        partial void OnSurveyTypeChanging(global::System.String value);
        partial void OnSurveyTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OSELS_EWEModel", "FK_SurveyMetaData_lk_SurveyType", "SurveyMetaData")]
        public EntityCollection<SurveyMetaData> SurveyMetaDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SurveyMetaData>("OSELS_EWEModel.FK_SurveyMetaData_lk_SurveyType", "SurveyMetaData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SurveyMetaData>("OSELS_EWEModel.FK_SurveyMetaData_lk_SurveyType", "SurveyMetaData", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OSELS_EWEModel", Name="Organization")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Organization : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Organization object.
        /// </summary>
        /// <param name="organizationId">Initial value of the OrganizationId property.</param>
        /// <param name="organizationKey">Initial value of the OrganizationKey property.</param>
        /// <param name="organization1">Initial value of the Organization1 property.</param>
        /// <param name="isEnabled">Initial value of the IsEnabled property.</param>
        /// <param name="isHostOrganization">Initial value of the IsHostOrganization property.</param>
        public static Organization CreateOrganization(global::System.Int32 organizationId, global::System.String organizationKey, global::System.String organization1, global::System.Boolean isEnabled, global::System.Boolean isHostOrganization)
        {
            Organization organization = new Organization();
            organization.OrganizationId = organizationId;
            organization.OrganizationKey = organizationKey;
            organization.Organization1 = organization1;
            organization.IsEnabled = isEnabled;
            organization.IsHostOrganization = isHostOrganization;
            return organization;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                if (_OrganizationId != value)
                {
                    OnOrganizationIdChanging(value);
                    ReportPropertyChanging("OrganizationId");
                    _OrganizationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrganizationId");
                    OnOrganizationIdChanged();
                }
            }
        }
        private global::System.Int32 _OrganizationId;
        partial void OnOrganizationIdChanging(global::System.Int32 value);
        partial void OnOrganizationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrganizationKey
        {
            get
            {
                return _OrganizationKey;
            }
            set
            {
                OnOrganizationKeyChanging(value);
                ReportPropertyChanging("OrganizationKey");
                _OrganizationKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrganizationKey");
                OnOrganizationKeyChanged();
            }
        }
        private global::System.String _OrganizationKey;
        partial void OnOrganizationKeyChanging(global::System.String value);
        partial void OnOrganizationKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Organization1
        {
            get
            {
                return _Organization1;
            }
            set
            {
                OnOrganization1Changing(value);
                ReportPropertyChanging("Organization1");
                _Organization1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Organization1");
                OnOrganization1Changed();
            }
        }
        private global::System.String _Organization1;
        partial void OnOrganization1Changing(global::System.String value);
        partial void OnOrganization1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEnabled
        {
            get
            {
                return _IsEnabled;
            }
            set
            {
                OnIsEnabledChanging(value);
                ReportPropertyChanging("IsEnabled");
                _IsEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnabled");
                OnIsEnabledChanged();
            }
        }
        private global::System.Boolean _IsEnabled;
        partial void OnIsEnabledChanging(global::System.Boolean value);
        partial void OnIsEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsHostOrganization
        {
            get
            {
                return _IsHostOrganization;
            }
            set
            {
                OnIsHostOrganizationChanging(value);
                ReportPropertyChanging("IsHostOrganization");
                _IsHostOrganization = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsHostOrganization");
                OnIsHostOrganizationChanged();
            }
        }
        private global::System.Boolean _IsHostOrganization;
        partial void OnIsHostOrganizationChanging(global::System.Boolean value);
        partial void OnIsHostOrganizationChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OSELS_EWEModel", "FK_Admin_Organization", "Admin")]
        public EntityCollection<Admin> Admins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Admin>("OSELS_EWEModel.FK_Admin_Organization", "Admin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Admin>("OSELS_EWEModel.FK_Admin_Organization", "Admin", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OSELS_EWEModel", "FK_SurveyMetaData_Organization", "SurveyMetaData")]
        public EntityCollection<SurveyMetaData> SurveyMetaDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SurveyMetaData>("OSELS_EWEModel.FK_SurveyMetaData_Organization", "SurveyMetaData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SurveyMetaData>("OSELS_EWEModel.FK_SurveyMetaData_Organization", "SurveyMetaData", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OSELS_EWEModel", Name="SurveyMetaData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SurveyMetaData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SurveyMetaData object.
        /// </summary>
        /// <param name="surveyId">Initial value of the SurveyId property.</param>
        /// <param name="surveyTypeId">Initial value of the SurveyTypeId property.</param>
        /// <param name="closingDate">Initial value of the ClosingDate property.</param>
        /// <param name="surveyName">Initial value of the SurveyName property.</param>
        /// <param name="templateXML">Initial value of the TemplateXML property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="templateXMLSize">Initial value of the TemplateXMLSize property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="organizationId">Initial value of the OrganizationId property.</param>
        /// <param name="isDraftMode">Initial value of the IsDraftMode property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        public static SurveyMetaData CreateSurveyMetaData(global::System.Guid surveyId, global::System.Int32 surveyTypeId, global::System.DateTime closingDate, global::System.String surveyName, global::System.String templateXML, global::System.Guid userID, global::System.Int64 templateXMLSize, global::System.DateTime dateCreated, global::System.Int32 organizationId, global::System.Boolean isDraftMode, global::System.DateTime startDate)
        {
            SurveyMetaData surveyMetaData = new SurveyMetaData();
            surveyMetaData.SurveyId = surveyId;
            surveyMetaData.SurveyTypeId = surveyTypeId;
            surveyMetaData.ClosingDate = closingDate;
            surveyMetaData.SurveyName = surveyName;
            surveyMetaData.TemplateXML = templateXML;
            surveyMetaData.UserID = userID;
            surveyMetaData.TemplateXMLSize = templateXMLSize;
            surveyMetaData.DateCreated = dateCreated;
            surveyMetaData.OrganizationId = organizationId;
            surveyMetaData.IsDraftMode = isDraftMode;
            surveyMetaData.StartDate = startDate;
            return surveyMetaData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SurveyId
        {
            get
            {
                return _SurveyId;
            }
            set
            {
                if (_SurveyId != value)
                {
                    OnSurveyIdChanging(value);
                    ReportPropertyChanging("SurveyId");
                    _SurveyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SurveyId");
                    OnSurveyIdChanged();
                }
            }
        }
        private global::System.Guid _SurveyId;
        partial void OnSurveyIdChanging(global::System.Guid value);
        partial void OnSurveyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SurveyNumber
        {
            get
            {
                return _SurveyNumber;
            }
            set
            {
                OnSurveyNumberChanging(value);
                ReportPropertyChanging("SurveyNumber");
                _SurveyNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SurveyNumber");
                OnSurveyNumberChanged();
            }
        }
        private global::System.String _SurveyNumber;
        partial void OnSurveyNumberChanging(global::System.String value);
        partial void OnSurveyNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SurveyTypeId
        {
            get
            {
                return _SurveyTypeId;
            }
            set
            {
                OnSurveyTypeIdChanging(value);
                ReportPropertyChanging("SurveyTypeId");
                _SurveyTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurveyTypeId");
                OnSurveyTypeIdChanged();
            }
        }
        private global::System.Int32 _SurveyTypeId;
        partial void OnSurveyTypeIdChanging(global::System.Int32 value);
        partial void OnSurveyTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ClosingDate
        {
            get
            {
                return _ClosingDate;
            }
            set
            {
                OnClosingDateChanging(value);
                ReportPropertyChanging("ClosingDate");
                _ClosingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClosingDate");
                OnClosingDateChanged();
            }
        }
        private global::System.DateTime _ClosingDate;
        partial void OnClosingDateChanging(global::System.DateTime value);
        partial void OnClosingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SurveyName
        {
            get
            {
                return _SurveyName;
            }
            set
            {
                OnSurveyNameChanging(value);
                ReportPropertyChanging("SurveyName");
                _SurveyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SurveyName");
                OnSurveyNameChanged();
            }
        }
        private global::System.String _SurveyName;
        partial void OnSurveyNameChanging(global::System.String value);
        partial void OnSurveyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrganizationName
        {
            get
            {
                return _OrganizationName;
            }
            set
            {
                OnOrganizationNameChanging(value);
                ReportPropertyChanging("OrganizationName");
                _OrganizationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrganizationName");
                OnOrganizationNameChanged();
            }
        }
        private global::System.String _OrganizationName;
        partial void OnOrganizationNameChanging(global::System.String value);
        partial void OnOrganizationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IntroductionText
        {
            get
            {
                return _IntroductionText;
            }
            set
            {
                OnIntroductionTextChanging(value);
                ReportPropertyChanging("IntroductionText");
                _IntroductionText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IntroductionText");
                OnIntroductionTextChanged();
            }
        }
        private global::System.String _IntroductionText;
        partial void OnIntroductionTextChanging(global::System.String value);
        partial void OnIntroductionTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TemplateXML
        {
            get
            {
                return _TemplateXML;
            }
            set
            {
                OnTemplateXMLChanging(value);
                ReportPropertyChanging("TemplateXML");
                _TemplateXML = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TemplateXML");
                OnTemplateXMLChanged();
            }
        }
        private global::System.String _TemplateXML;
        partial void OnTemplateXMLChanging(global::System.String value);
        partial void OnTemplateXMLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExitText
        {
            get
            {
                return _ExitText;
            }
            set
            {
                OnExitTextChanging(value);
                ReportPropertyChanging("ExitText");
                _ExitText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExitText");
                OnExitTextChanged();
            }
        }
        private global::System.String _ExitText;
        partial void OnExitTextChanging(global::System.String value);
        partial void OnExitTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Guid _UserID;
        partial void OnUserIDChanging(global::System.Guid value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TemplateXMLSize
        {
            get
            {
                return _TemplateXMLSize;
            }
            set
            {
                OnTemplateXMLSizeChanging(value);
                ReportPropertyChanging("TemplateXMLSize");
                _TemplateXMLSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TemplateXMLSize");
                OnTemplateXMLSizeChanged();
            }
        }
        private global::System.Int64 _TemplateXMLSize;
        partial void OnTemplateXMLSizeChanging(global::System.Int64 value);
        partial void OnTemplateXMLSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                OnOrganizationIdChanging(value);
                ReportPropertyChanging("OrganizationId");
                _OrganizationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrganizationId");
                OnOrganizationIdChanged();
            }
        }
        private global::System.Int32 _OrganizationId;
        partial void OnOrganizationIdChanging(global::System.Int32 value);
        partial void OnOrganizationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDraftMode
        {
            get
            {
                return _IsDraftMode;
            }
            set
            {
                OnIsDraftModeChanging(value);
                ReportPropertyChanging("IsDraftMode");
                _IsDraftMode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDraftMode");
                OnIsDraftModeChanged();
            }
        }
        private global::System.Boolean _IsDraftMode;
        partial void OnIsDraftModeChanging(global::System.Boolean value);
        partial void OnIsDraftModeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OSELS_EWEModel", "FK_SurveyMetaData_lk_SurveyType", "lk_SurveyType")]
        public lk_SurveyType lk_SurveyType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lk_SurveyType>("OSELS_EWEModel.FK_SurveyMetaData_lk_SurveyType", "lk_SurveyType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lk_SurveyType>("OSELS_EWEModel.FK_SurveyMetaData_lk_SurveyType", "lk_SurveyType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lk_SurveyType> lk_SurveyTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lk_SurveyType>("OSELS_EWEModel.FK_SurveyMetaData_lk_SurveyType", "lk_SurveyType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lk_SurveyType>("OSELS_EWEModel.FK_SurveyMetaData_lk_SurveyType", "lk_SurveyType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OSELS_EWEModel", "FK_SurveyMetaData_Organization", "Organization")]
        public Organization Organization
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("OSELS_EWEModel.FK_SurveyMetaData_Organization", "Organization").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("OSELS_EWEModel.FK_SurveyMetaData_Organization", "Organization").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Organization> OrganizationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("OSELS_EWEModel.FK_SurveyMetaData_Organization", "Organization");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Organization>("OSELS_EWEModel.FK_SurveyMetaData_Organization", "Organization", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OSELS_EWEModel", "FK_SurveyResponse_SurveyMetaData", "SurveyResponse")]
        public EntityCollection<SurveyResponse> SurveyResponses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SurveyResponse>("OSELS_EWEModel.FK_SurveyResponse_SurveyMetaData", "SurveyResponse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SurveyResponse>("OSELS_EWEModel.FK_SurveyResponse_SurveyMetaData", "SurveyResponse", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OSELS_EWEModel", Name="SurveyResponse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SurveyResponse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SurveyResponse object.
        /// </summary>
        /// <param name="responseId">Initial value of the ResponseId property.</param>
        /// <param name="surveyId">Initial value of the SurveyId property.</param>
        /// <param name="dateUpdated">Initial value of the DateUpdated property.</param>
        /// <param name="statusId">Initial value of the StatusId property.</param>
        /// <param name="responseXML">Initial value of the ResponseXML property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="isDraftMode">Initial value of the IsDraftMode property.</param>
        public static SurveyResponse CreateSurveyResponse(global::System.Guid responseId, global::System.Guid surveyId, global::System.DateTime dateUpdated, global::System.Int32 statusId, global::System.String responseXML, global::System.DateTime dateCreated, global::System.Boolean isDraftMode)
        {
            SurveyResponse surveyResponse = new SurveyResponse();
            surveyResponse.ResponseId = responseId;
            surveyResponse.SurveyId = surveyId;
            surveyResponse.DateUpdated = dateUpdated;
            surveyResponse.StatusId = statusId;
            surveyResponse.ResponseXML = responseXML;
            surveyResponse.DateCreated = dateCreated;
            surveyResponse.IsDraftMode = isDraftMode;
            return surveyResponse;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ResponseId
        {
            get
            {
                return _ResponseId;
            }
            set
            {
                if (_ResponseId != value)
                {
                    OnResponseIdChanging(value);
                    ReportPropertyChanging("ResponseId");
                    _ResponseId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResponseId");
                    OnResponseIdChanged();
                }
            }
        }
        private global::System.Guid _ResponseId;
        partial void OnResponseIdChanging(global::System.Guid value);
        partial void OnResponseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SurveyId
        {
            get
            {
                return _SurveyId;
            }
            set
            {
                OnSurveyIdChanging(value);
                ReportPropertyChanging("SurveyId");
                _SurveyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurveyId");
                OnSurveyIdChanged();
            }
        }
        private global::System.Guid _SurveyId;
        partial void OnSurveyIdChanging(global::System.Guid value);
        partial void OnSurveyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private global::System.DateTime _DateUpdated;
        partial void OnDateUpdatedChanging(global::System.DateTime value);
        partial void OnDateUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCompleted
        {
            get
            {
                return _DateCompleted;
            }
            set
            {
                OnDateCompletedChanging(value);
                ReportPropertyChanging("DateCompleted");
                _DateCompleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCompleted");
                OnDateCompletedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCompleted;
        partial void OnDateCompletedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                OnStatusIdChanging(value);
                ReportPropertyChanging("StatusId");
                _StatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusId");
                OnStatusIdChanged();
            }
        }
        private global::System.Int32 _StatusId;
        partial void OnStatusIdChanging(global::System.Int32 value);
        partial void OnStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ResponseXML
        {
            get
            {
                return _ResponseXML;
            }
            set
            {
                OnResponseXMLChanging(value);
                ReportPropertyChanging("ResponseXML");
                _ResponseXML = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ResponseXML");
                OnResponseXMLChanged();
            }
        }
        private global::System.String _ResponseXML;
        partial void OnResponseXMLChanging(global::System.String value);
        partial void OnResponseXMLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResponsePasscode
        {
            get
            {
                return _ResponsePasscode;
            }
            set
            {
                OnResponsePasscodeChanging(value);
                ReportPropertyChanging("ResponsePasscode");
                _ResponsePasscode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResponsePasscode");
                OnResponsePasscodeChanged();
            }
        }
        private global::System.String _ResponsePasscode;
        partial void OnResponsePasscodeChanging(global::System.String value);
        partial void OnResponsePasscodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ResponseXMLSize
        {
            get
            {
                return _ResponseXMLSize;
            }
            set
            {
                OnResponseXMLSizeChanging(value);
                ReportPropertyChanging("ResponseXMLSize");
                _ResponseXMLSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResponseXMLSize");
                OnResponseXMLSizeChanged();
            }
        }
        private Nullable<global::System.Int64> _ResponseXMLSize;
        partial void OnResponseXMLSizeChanging(Nullable<global::System.Int64> value);
        partial void OnResponseXMLSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDraftMode
        {
            get
            {
                return _IsDraftMode;
            }
            set
            {
                OnIsDraftModeChanging(value);
                ReportPropertyChanging("IsDraftMode");
                _IsDraftMode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDraftMode");
                OnIsDraftModeChanged();
            }
        }
        private global::System.Boolean _IsDraftMode;
        partial void OnIsDraftModeChanging(global::System.Boolean value);
        partial void OnIsDraftModeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OSELS_EWEModel", "FK_SurveyResponse_lk_Status", "lk_Status")]
        public lk_Status lk_Status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lk_Status>("OSELS_EWEModel.FK_SurveyResponse_lk_Status", "lk_Status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lk_Status>("OSELS_EWEModel.FK_SurveyResponse_lk_Status", "lk_Status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lk_Status> lk_StatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lk_Status>("OSELS_EWEModel.FK_SurveyResponse_lk_Status", "lk_Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lk_Status>("OSELS_EWEModel.FK_SurveyResponse_lk_Status", "lk_Status", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OSELS_EWEModel", "FK_SurveyResponse_SurveyMetaData", "SurveyMetaData")]
        public SurveyMetaData SurveyMetaData
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyMetaData>("OSELS_EWEModel.FK_SurveyResponse_SurveyMetaData", "SurveyMetaData").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyMetaData>("OSELS_EWEModel.FK_SurveyResponse_SurveyMetaData", "SurveyMetaData").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SurveyMetaData> SurveyMetaDataReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyMetaData>("OSELS_EWEModel.FK_SurveyResponse_SurveyMetaData", "SurveyMetaData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SurveyMetaData>("OSELS_EWEModel.FK_SurveyResponse_SurveyMetaData", "SurveyMetaData", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
