//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class lk_Status
    {
        public lk_Status()
        {
            this.SurveyResponses = new HashSet<SurveyResponse>();
        }
    
        public int StatusId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<SurveyResponse> SurveyResponses { get; set; }
    }
}
