//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseXml
    {
        public System.Guid ResponseId { get; set; }
        public string Xml { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsNewRecord { get; set; }
    }
}
