//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UserOrganizations = new HashSet<UserOrganization>();
        }
    
        public int RoleID { get; set; }
        public int RoleValue { get; set; }
        public string RoleDescription { get; set; }
    
        public virtual ICollection<UserOrganization> UserOrganizations { get; set; }
    }
}
