//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyReportsInfo
    {
        public SurveyReportsInfo()
        {
            this.SurveyReports = new HashSet<SurveyReport>();
        }
    
        public System.Guid ReportId { get; set; }
        public System.Guid SurveyId { get; set; }
        public int ReportVersion { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateEdited { get; set; }
        public string DataSource { get; set; }
        public int RecordCount { get; set; }
        public string ReportName { get; set; }
    
        public virtual SurveyMetaData SurveyMetaData { get; set; }
        public virtual ICollection<SurveyReport> SurveyReports { get; set; }
    }
}
