//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResponseTracking
    {
        public System.Guid ResponseId { get; set; }
        public bool IsSQLResponse { get; set; }
        public bool IsResponseinsertedToEpi7 { get; set; }
    
        public virtual SurveyResponse SurveyResponse { get; set; }
    }
}
