//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.SurveyMetaDatas = new HashSet<SurveyMetaData>();
            this.UserOrganizations = new HashSet<UserOrganization>();
            this.SurveyResponses = new HashSet<SurveyResponse>();
            this.Canvas = new HashSet<Canva>();
            this.SharedCanvases = new HashSet<SharedCanvas>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PasswordHash { get; set; }
        public bool ResetPassword { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.Guid> UGuid { get; set; }
    
        public virtual ICollection<SurveyMetaData> SurveyMetaDatas { get; set; }
        public virtual ICollection<UserOrganization> UserOrganizations { get; set; }
        public virtual ICollection<SurveyResponse> SurveyResponses { get; set; }
        public virtual ICollection<Canva> Canvas { get; set; }
        public virtual ICollection<SharedCanvas> SharedCanvases { get; set; }
    }
}
