//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrganization
    {
        public int UserID { get; set; }
        public int OrganizationID { get; set; }
        public int RoleId { get; set; }
        public bool Active { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
